/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplBotones = new javax.swing.JTabbedPane();
        jpLibro = new javax.swing.JPanel();
        btnInsertarLibroM = new javax.swing.JButton();
        btnEliminarLibroM = new javax.swing.JButton();
        btnModificarLibroM = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMostrarLibro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jpAutor = new javax.swing.JPanel();
        btnInsertarAutorM = new javax.swing.JButton();
        btnEliminarAutorM = new javax.swing.JButton();
        btnModificarAutorM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarAutor = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnMostrarAutorM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInsertarLibroM.setText("Insertar");

        btnEliminarLibroM.setText("Eliminar");

        btnModificarLibroM.setText("Modificar");

        DefaultTableModel model = new DefaultTableModel();
        tblMostrarLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblMostrarLibro);

        jLabel1.setText("Datos de la tabla Libros");

        javax.swing.GroupLayout jpLibroLayout = new javax.swing.GroupLayout(jpLibro);
        jpLibro.setLayout(jpLibroLayout);
        jpLibroLayout.setHorizontalGroup(
            jpLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLibroLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpLibroLayout.createSequentialGroup()
                        .addComponent(btnInsertarLibroM)
                        .addGap(94, 94, 94)
                        .addComponent(btnEliminarLibroM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificarLibroM)
                        .addGap(27, 27, 27))))
            .addGroup(jpLibroLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addGap(0, 169, Short.MAX_VALUE))
        );
        jpLibroLayout.setVerticalGroup(
            jpLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarLibroM)
                    .addComponent(btnEliminarLibroM)
                    .addComponent(btnModificarLibroM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jplBotones.addTab("Libro", jpLibro);

        btnInsertarAutorM.setText("Insertar");

        btnEliminarAutorM.setText("Eliminar");

        btnModificarAutorM.setText("Modificar");

        DefaultTableModel model2 = new DefaultTableModel();
        tblMostrarAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMostrarAutor);

        jLabel2.setText("Datos de la tabla Autor");

        btnMostrarAutorM.setText("Mostrar Join");

        javax.swing.GroupLayout jpAutorLayout = new javax.swing.GroupLayout(jpAutor);
        jpAutor.setLayout(jpAutorLayout);
        jpAutorLayout.setHorizontalGroup(
            jpAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAutorLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpAutorLayout.createSequentialGroup()
                        .addComponent(btnInsertarAutorM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarAutorM)
                        .addGap(94, 94, 94)
                        .addComponent(btnModificarAutorM)
                        .addGap(26, 26, 26))))
            .addGroup(jpAutorLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAutorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMostrarAutorM)
                .addContainerGap())
        );
        jpAutorLayout.setVerticalGroup(
            jpAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarAutorM)
                    .addComponent(btnEliminarAutorM)
                    .addComponent(btnModificarAutorM))
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarAutorM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jplBotones.addTab("Autor", jpAutor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jplBotones)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jplBotones)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminarAutorM;
    public javax.swing.JButton btnEliminarLibroM;
    public javax.swing.JButton btnInsertarAutorM;
    public javax.swing.JButton btnInsertarLibroM;
    public javax.swing.JButton btnModificarAutorM;
    public javax.swing.JButton btnModificarLibroM;
    public javax.swing.JButton btnMostrarAutorM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpAutor;
    private javax.swing.JPanel jpLibro;
    private javax.swing.JTabbedPane jplBotones;
    public javax.swing.JTable tblMostrarAutor;
    public javax.swing.JTable tblMostrarLibro;
    // End of variables declaration//GEN-END:variables
}
